# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

#
# COMMON VARIABLES
# https://megalinter.io/v6/configuration/#common-variables
#

ENABLE:
  - MARKDOWN
  - SPELL
  - YAML

FILTER_REGEX_INCLUDE: (_posts/|.linters/|.mega-linter.yml)
LINTER_RULES_PATH: '.linters/'

PRINT_ALPACA: false
PRINT_ALL_FILES: true

APPLY_FIXES:
 - YAML_PRETTIER

#
# MARKDOWN
# https://megalinter.io/v6/descriptors/markdown/
#
MARKDOWN_FILTER_REGEX_INCLUDE: (_posts/)

# Linter name:       MarkdownLint
# Linter version:    0.33.0
# Linter config:     https://github.com/DavidAnson/markdownlint#readme
# MegaLinter config: https://megalinter.io/v6/descriptors/markdown_markdownlint/
MARKDOWN_MARKDOWNLINT_CONFIG_FILE: 'markdown/markdownlint.yaml'

# Linter name:       markdown-link-check
# Linter version:    3.10.3
# Linter config:     https://github.com/tcort/markdown-link-check#readme
# MegaLinter config: https://megalinter.io/v6/descriptors/markdown_markdown_link_check/
MARKDOWN_MARKDOWN_LINK_CHECK_CONFIG_FILE: 'markdown/markdown-link-check.json'

# Linter name:       markdown-table-formatter
# Linter version:    1.4.0
# Linter config:     https://github.com/nvuillam/markdown-table-formatter#readme
# MegaLinter config: https://megalinter.io/v6/descriptors/markdown_markdown_table_formatter/


#
# SPELL
# https://megalinter.io/7.7.0/descriptors/spell/
#
SPELL_FILTER_REGEX_INCLUDE: (_posts/)

# Linter name:       cspell
# Linter version:    8.1.3
# Linter config:     https://cspell.org/configuration/
# MegaLinter config: https://megalinter.io/7.7.0/descriptors/spell_cspell/
SPELL_CSPELL_CONFIG_FILE: 'spell/cspell/cspell.yaml'

# Linter name:       proselint
# Linter version:    0.13.0
# Linter config:     https://github.com/amperser/proselint#readme
# MegaLinter config: https://megalinter.io/7.7.0/descriptors/spell_proselint/
SPELL_PROSELINT_RULES_PATH: '.linters/spell/'

# Linter name:       vale
# Linter version:    2.30.0
# Linter config:     https://github.com/errata-ai/vale
# MegaLinter config: https://megalinter.io/7.7.0/descriptors/spell_vale/
SPELL_VALE_PRE_COMMANDS:
  - command: 'vale sync'
    cwd: 'workspace'
SPELL_VALE_CONFIG_FILE: '.vale.ini'

# Linter name:       lychee
# Linter version:    0.13.0
# Linter config:     https://lychee.cli.rs/#/usage/config
# MegaLinter config: https://megalinter.io/7.7.0/descriptors/spell_lychee/
SPELL_LYCHEE_CONFIG_FILE: 'spell/lychee.toml'

#
# YAML
# https://megalinter.io/v6/descriptors/yaml/
#
YAML_FILTER_REGEX_INCLUDE: (.linters/|.mega-linter.yml)

# Linter name:       prettier
# Linter version:    2.8.1
# Linter config:     https://prettier.io/docs/en/configuration.html
# MegaLinter config: https://megalinter.io/v6/descriptors/yaml_prettier/
YAML_PRETTIER_CONFIG_FILE: 'yaml/prettierrc.yaml'

# Linter name:       yamllint
# Linter version:    1.28.0
# Linter config:     https://yamllint.readthedocs.io/en/stable/configuration.html#configuration
# MegaLinter config: https://megalinter.io/v6/descriptors/yaml_yamllint/
YAML_YAMLLINT_CONFIG_FILE: 'yaml/yamllint.yaml'

# Linter name:       v8r
# Linter version:    0.13.1
# Linter config:     https://github.com/chris48s/v8r#configuration
# MegaLinter config: https://megalinter.io/v6/descriptors/yaml_v8r/
YAML_V8R_CLI_LINT_MODE: 'project'
