# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

#
# COMMON VARIABLES
# https://megalinter.io/v6/configuration/#common-variables
#

ENABLE:
  - MARKDOWN
  - SPELL

FILTER_REGEX_INCLUDE: '_posts/'
LINTER_RULES_PATH: '.linters/'

PRINT_ALPACA: false
PRINT_ALL_FILES: true
